# Generated by Django 5.2.6 on 2025-10-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_course_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_by',
        ),
    ]
