# Generated by Django 5.2.6 on 2025-10-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_remove_course_created_by'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dashboardalert',
            table='ui_dashboardalert',
        ),
        migrations.AlterModelTable(
            name='emaillog',
            table='ui_emaillog',
        ),
        migrations.AlterModelTable(
            name='notificationpreference',
            table='ui_notificationpreference',
        ),
    ]
