# Generated by Django 5.2.6 on 2025-10-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_alter_quizattempt_quiz_alter_quizattempt_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken',
            field=models.IntegerField(default=0, help_text='Time taken in minutes'),
        ),
    ]
