# Generated by Django 5.2.6 on 2025-10-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_quizattempt_time_taken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_retake',
            field=models.BooleanField(default=False),
        ),
    ]
