# Generated by Django 5.2.6 on 2025-10-24 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_studentanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('type', models.CharField(choices=[('completed_course', 'Completed Course'), ('not_started_course', 'Not Started Course'), ('in_progress_course', 'In Progress Course'), ('quiz_improvement', 'Quiz Improvement'), ('quiz_good', 'Quiz Good Performance'), ('quiz_excellent', 'Quiz Excellent Performance'), ('welcome', 'Welcome'), ('consistency', 'Consistency'), ('course', 'Course Recommendation')], max_length=50)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('action', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.course')),
                ('related_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.quiz')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ui_recommendation',
                'ordering': ['-created_at'],
            },
        ),
    ]
