# Generated by Django 5.2.6 on 2025-10-25 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighCompletionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high_completion', 'High Completion (75%+)'), ('almost_complete', 'Almost Complete (90%+)'), ('completion_urgent', 'Completion Urgent (95%+)')], default='high_completion', max_length=50)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.course')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='high_completion_alerts', to=settings.AUTH_USER_MODEL)),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.studentcourse')),
            ],
            options={
                'db_table': 'ui_highcompletionalert',
                'ordering': ['-priority', '-created_at'],
                'unique_together': {('student', 'student_course', 'is_active')},
            },
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
